# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  version1:
    name: Test on nodejs Version 12.x
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "12.x"
        cache: 'npm'
    - run: npm ci
    - run: npm test

  version2: 
    name: Test on nodejs Version 14.x
    runs-on: ubuntu-latest
    needs: [version1]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: "14.x"
        cache: 'npm'
    - run: npm ci
    - run: npm test

  version3:
    name: Test on nodejs Version 16.x
    runs-on: ubuntu-latest
    needs: [version2]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"
        cache: 'npm'
    - run: npm ci
    - run: npm test
